### ISSUE TITLE
Question: We have .exe and .dmg for installing the wallet for windows and mac OS, right?

### ISSUE THREAD

**Issue by Hyjaz** [Electraproject/documents#1]
@camill-a We do have a .dmg and .exe for mac and windows os right?
This(build_guide.md) might be a little overwhelming for those who are not inclined in software...

However it is great!

**Comment by camill-a** [comment]
Yes, it's a bit heavy, it may not be usefull to all. Just collecting documents here, was an existing PDF that I translated to markdown.
